"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import sys
from pathlib import Path
import tzlocal

PROJECT_PATH = (
    Path(__file__).resolve().parent.parent.parent
)  # path to the root of the project
sys.path.append(f"{PROJECT_PATH}")

from backend.protzilla.constants.paths import (
    UPLOAD_PATH,
    PROJECT_PATH,
    BACKEND_PATH,
    FRONTEND_PATH,
)

FILE_UPLOAD_HANDLERS = ["main.upload_handler.CustomFileUploadHandler"]

FILE_UPLOAD_TEMP_DIR = UPLOAD_PATH
if not os.path.exists(FILE_UPLOAD_TEMP_DIR):
    print("creating nonexistent", FILE_UPLOAD_TEMP_DIR)
    os.makedirs(FILE_UPLOAD_TEMP_DIR)

if not os.path.exists(UPLOAD_PATH):
    print("creating nonexistent ", UPLOAD_PATH)
    os.makedirs(UPLOAD_PATH)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^b(z4a%_42zo=feur29^g5sz9+7a(gcqq_l8vgkd$og36@+x5f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", False)

ALLOWED_HOSTS = ["0.0.0.0", "127.0.0.1", "localhost", "django"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [FRONTEND_PATH / "dist"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:6006",
    "http://127.0.0.1:6006",
]

# Cross-Orgin Resource Sharing
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # pnpm start
    "http://127.0.0.1:5173",  # pnpm start
    "http://localhost:6006",  # Storybook
    "http://127.0.0.1:6006",  # Storybook
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "X-CSRFToken",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_COOKIE_NAME = "csrftoken"  # The name of the CSRF cookie
CSRF_COOKIE_DOMAIN = None  # Allow any domain
CSRF_COOKIE_HTTPONLY = (
    False  # Set to True if you want the cookie to be inaccessible to JavaScript
)
CSRF_COOKIE_SECURE = False  # Set to True if you are using HTTPS
CSRF_COOKIE_SAMESITE = "Lax"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BACKEND_PATH / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

local_timezone = tzlocal.get_localzone()
TIME_ZONE = str(local_timezone)

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    FRONTEND_PATH / "dist",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# This configures the django logger
# to adjust the protzilla-logger, see protzilla.constants.protzilla_logging for more info
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "django": {
            "level": "INFO",
            "class": "backend.protzilla.constants.protzilla_logging.ProtzillaLoggingHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["django"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
