import numpy as np
import pandas as pd
import plotly.colors
import plotly.graph_objects as go
from dataclasses import dataclass
from enum import StrEnum
from numpy import log2
from tqdm import tqdm

from backend.protzilla.constants.colors import PLOT_PRIMARY_COLOR
from backend.protzilla.utilities.utilities import default_intensity_column

INTENSITY_COLOR_SCALE = plotly.colors.sequential.Cividis
SEQUENCE_DEPTH_PEPTIDE_SPACING = 1


class IntensityNormalization(StrEnum):
    min_max_scaling = "min_max_scaling"
    none = "none"


class AggregationMethod(StrEnum):
    median = "median"
    mean = "mean"


@dataclass(unsafe_hash=True)
class PeptideMatch:
    peptide_sequence: str
    start_location_on_protein: int
    end_location_on_protein: int
    intensity: float = 0.0
    metadata_group: str = ""


@dataclass(unsafe_hash=True)
class ProteinHit:
    protein_id: str
    start_location_on_protein: int
    end_location_on_protein: int


def build_kmer_dictionary(
    protein_dictionary: dict[str, str], k: int = 5
) -> dict[str, list[tuple[str, int]]]:
    """
    Builds a dictionary of all kmers in a list of protein sequences. The kmers are generated by sliding a window of size
    k along the protein sequences. The dictionary maps the k-mer to a list of tuples containing the protein ID and
    the index of the k-mer in the protein sequence.

    :param protein_dictionary: A dictionary mapping protein IDs to protein sequences.
    :param k: The size of the k-mers to generate.

    :return: A dictionary mapping k-mers to a list of tuples containing the protein ID and the index of the k-mer in the
    protein sequence.
    """
    # if the dictionary already exists, load it from disk
    kmer_dict = {}
    for protein_id, protein_sequence in tqdm(
        protein_dictionary.items(),
        desc="Building kmer dictionary",
        unit_scale=True,
        unit="protein",
    ):
        for i in range(len(protein_sequence) - k + 1):
            kmer = protein_sequence[i : i + k]
            if kmer in kmer_dict:
                kmer_dict[kmer].append((protein_id, i))
            else:
                kmer_dict[kmer] = [(protein_id, i)]
    return kmer_dict


def match_peptide_to_protein_ids(
    peptide_sequence: str,
    protein_kmer_dictionary: dict[str, list[tuple[str, int]]],
    protein_dictionary: dict[str, str],
) -> list[ProteinHit]:
    """
    Matches a peptide sequence to a dictionary of kmers in protein sequences.

    :param peptide_sequence: The peptide sequence to match.
    :param protein_kmer_dictionary: A dictionary mapping k-mers to a list of tuples containing the protein ID and the
    index of the k-mer in the protein sequence.
    :param protein_dictionary: A dictionary mapping protein IDs to protein sequences.

    :return: A list of ProteinHit objects containing the protein ID and the start location of the peptide on the
    protein.
    """
    if len(peptide_sequence) == 0:
        raise ValueError("Peptide sequence is empty.")
    # infer k from the kmer dictionary
    k = len(list(protein_kmer_dictionary.keys())[0])
    peptide_kmers = [
        peptide_sequence[i : i + k] for i in range(len(peptide_sequence) - k + 1)
    ]
    first_kmer, last_kmer = peptide_kmers[0], peptide_kmers[-1]
    # match the kmers
    first_kmer_matches = protein_kmer_dictionary.get(first_kmer, [])
    last_kmer_matches = protein_kmer_dictionary.get(last_kmer, [])
    if first_kmer_matches == [] or last_kmer_matches == []:
        return []

    hits = []
    for protein_id_a, start_first_kmer in first_kmer_matches:
        for protein_id_b, start_last_kmer in last_kmer_matches:
            if protein_id_a != protein_id_b:
                continue
            expected_last_start = start_first_kmer + len(peptide_sequence) - k
            if start_last_kmer != expected_last_start:
                continue
            start = start_first_kmer
            end = start_first_kmer + len(peptide_sequence)
            if protein_dictionary[protein_id_a][start:end] == peptide_sequence:
                hits.append(ProteinHit(protein_id_a, start, end))
    hits = list(set(hits))

    # Sanity checks
    for hit in hits:
        subsequence = protein_dictionary[hit.protein_id][
            hit.start_location_on_protein : hit.end_location_on_protein
        ]
        assert len(subsequence) == len(
            peptide_sequence
        ), f"Lengths do not match: {len(subsequence)} != {len(peptide_sequence)}"
        assert (
            subsequence in peptide_sequence
        ), f"Subsequence not in peptide sequence:\nA: {subsequence}\nB: {peptide_sequence}"
        assert (
            peptide_sequence in protein_dictionary[hit.protein_id]
        ), f"Peptide not in protein sequence: {peptide_sequence} not in {protein_dictionary[hit.protein_id]}"
    return hits


# --8<-- [start:plot_protein_coverage]
def plot_protein_coverage(
    fasta_df: pd.DataFrame,
    peptide_df: pd.DataFrame,
    metadata_df: pd.DataFrame,
    protein_id: str,
    grouping: str,
    selected_groups: list[str] = None,
    aggregation_method: AggregationMethod = AggregationMethod.median,
) -> dict[str, list[go.Figure]]:
    """
    Plots the coverage of a protein sequence by peptides. The resulting plot is divided into subplots for each group
    specified in the metadata dataframe. Each subplot shows the coverage of the protein sequence by peptides for
    samples in the group. The coverage is shown as a bar plot, with the height of each bar representing the number of
    peptides that cover that position in the protein sequence. Above the bar plot, the peptides are shown as rectangles,
    with the color of the rectangle representing the intensity of the peptide. The intensity is normalized
    between 0 and 1 for each group.

    :param fasta_df: DataFrame containing the protein sequences and their protein ids
    :param peptide_df: DataFrame containing the peptide sequences and their intensities
    :param metadata_df: DataFrame containing the sample metadata
    :param protein_id: The protein id to plot the coverage for
    :param grouping: The column in the metadata dataframe to group the samples by
    :param selected_groups: The groups to plot the coverage for, e.g. specific samples or treatment conditions
    :param aggregation_method: The method to aggregate peptide intensities when multiple peptides map to the same
    sequence

    :return: A dictionary containing the plotly figure for the protein coverage plot
    """
    if selected_groups is None or selected_groups == []:
        raise ValueError("No samples provided.")

    # add group information to the peptide dataframe
    peptide_df = peptide_df.merge(metadata_df, on="Sample")

    reduced_peptide_df = peptide_df[peptide_df[grouping].isin(selected_groups)].fillna(
        0
    )
    if len(reduced_peptide_df) == 0:
        raise ValueError("No peptides found for the samples provided.")

    protein_sequence_dict = dict(
        zip(fasta_df["Protein ID"], fasta_df["Protein Sequence"])
    )
    sequence_kmer_dict = build_kmer_dictionary(protein_sequence_dict)

    if len(sequence_kmer_dict) == 0:
        raise ValueError("K-mer dictionary is empty. Is the FASTA file valid?")
    if protein_id not in protein_sequence_dict:
        raise ValueError(f"Protein ID {protein_id} not found in protein dictionary.")

    protein_sequence = protein_sequence_dict[protein_id]
    peptide_matches = []
    coverage_by_group_name = {
        sample: [0] * len(protein_sequence) for sample in selected_groups
    }

    intensity_column = default_intensity_column(reduced_peptide_df)
    for (group_name, peptide_sequence), row in tqdm(
        reduced_peptide_df[[grouping, "Sequence", intensity_column]]
        .drop_duplicates()
        .groupby([grouping, "Sequence"]),
        desc="Matching peptides to protein",
        unit_scale=True,
        unit="peptide",
    ):
        sample = extract_peptide_from_slice(row, aggregation_method)
        if sample.empty:
            continue
        intensity = sample[intensity_column].values[0]
        protein_hits = match_peptide_to_protein_ids(
            peptide_sequence=peptide_sequence,
            protein_kmer_dictionary=sequence_kmer_dict,
            protein_dictionary=protein_sequence_dict,
        )
        # we only care about the hits pertaining to the argument-supplied protein id
        filtered_protein_hits = filter(
            lambda x: x.protein_id == protein_id, protein_hits
        )
        for protein_hit in filtered_protein_hits:
            # add the peptide sequence and location to the peptide matches pertaining to the protein id
            peptide_matches.append(
                PeptideMatch(
                    peptide_sequence=peptide_sequence,
                    start_location_on_protein=protein_hit.start_location_on_protein,
                    end_location_on_protein=protein_hit.end_location_on_protein,
                    intensity=log2(intensity),
                    metadata_group=group_name,
                )
            )
            # update the coverage of the protein sequence
            increment_coverage_inplace(coverage_by_group_name[group_name], protein_hit)

    if len(peptide_matches) == 0:
        raise ValueError(f"No peptides matched for protein {protein_id}")

    # now that all the matches have been determined with their start and end on the protein sequence, we need to find
    # an optimal solution for the location of their rectangles in the plot without overlap while minimizing the
    # required number of rows (vertical space)
    rows_by_group_name = distribute_to_rows(peptide_matches)

    figures = build_coverage_plot(
        coverages_by_group_name=coverage_by_group_name,
        protein_sequence=protein_sequence,
        rows_by_group_name=rows_by_group_name,
        grouping=grouping,
        aggregation_method=aggregation_method,
    )

    return {"plots": figures}


# --8<-- [end:plot_protein_coverage]


def build_coverage_plot(
    coverages_by_group_name: dict[str, list[int]],
    protein_sequence: str,
    rows_by_group_name: dict[str, list[list[PeptideMatch]]],
    grouping: str = "",
    aggregation_method: AggregationMethod = AggregationMethod.median,
) -> list[go.Figure]:
    """
    Creates separate plotly figures showing the coverage of a protein sequence by peptides for each group.

    :param coverages_by_group_name: A dictionary mapping group names to coverage lists (i.e., lists that show how many
    peptides cover each position in the protein sequence)
    :param protein_sequence: The protein sequence to plot the coverage for
    :param rows_by_group_name: A dictionary mapping group names to lists of peptide match rows
    :param grouping: The column in the metadata dataframe to group the samples by
    :param aggregation_method: The method to aggregate peptide intensities when multiple peptides map to the same
    sequence

    :return: A list of plotly figures, one for each group, showing the coverage of the protein sequence by peptides
    """

    protein_sequence_labels = [
        f"{amino_acid} - {amino_acid_index} "
        for amino_acid_index, amino_acid in enumerate(protein_sequence)
    ]
    max_coverage_value = get_max_coverage(coverages_by_group_name)

    figures = []

    # Create a separate figure for each group
    for group_name in rows_by_group_name.keys():
        peptide_rows = rows_by_group_name[group_name]
        coverage = coverages_by_group_name[group_name]

        # Create a new figure for this group
        fig = go.Figure()

        # Calculate the desired heights
        max_bar_height = max_coverage_value
        desired_peptide_height = max_bar_height * 2  # 1:2 ratio

        # Calculate the height scaling factor for peptides
        num_peptide_rows = len(peptide_rows)
        if num_peptide_rows > 0:
            # Include spacing in the calculation
            total_spacing = SEQUENCE_DEPTH_PEPTIDE_SPACING
            peptide_box_height = (
                desired_peptide_height - total_spacing
            ) / num_peptide_rows
        else:
            peptide_box_height = 1.0

        add_sequence_depth_to_plot(
            fig=fig,
            coverage=coverage,
            protein_sequence_labels=protein_sequence_labels,
        )

        # Peptide plot
        # Checking for -inf because these are the result of log-transforming 0 intensities, i.e., peptides that were
        # identified but not quantified. We want to plot them but assign them a default color as not to distort the
        # color scale for actual intensity values.
        current_group_intensities = [
            peptide_match.intensity
            for row in peptide_rows
            for peptide_match in row
            if peptide_match.intensity > -np.inf
        ]
        max_intensity = max(current_group_intensities)
        min_intensity = min(current_group_intensities)

        def scale_intensity(intensity):
            if intensity == -np.inf:
                return np.nan
            if max_intensity != min_intensity:
                return (intensity - min_intensity) / (max_intensity - min_intensity)
            return 0

        for row_index, row in enumerate(peptide_rows):
            for peptide_match in row:
                add_peptide_to_plot(
                    fig=fig,
                    normalized_intensity=scale_intensity(peptide_match.intensity),
                    peptide_match=peptide_match,
                    protein_sequence_labels=protein_sequence_labels,
                    row_index=row_index,
                    offset=max_coverage_value + SEQUENCE_DEPTH_PEPTIDE_SPACING,
                    box_height=peptide_box_height,
                    grouping=grouping,
                )

        # Update y-axis range to accommodate both the bar plot and peptide sections
        total_height = (
            max_coverage_value + SEQUENCE_DEPTH_PEPTIDE_SPACING + desired_peptide_height
        )

        fig.update_layout(
            title=f"Peptides of {group_name}",
            hovermode="closest",
            showlegend=False,
        )
        fig.update_yaxes(
            range=[0, total_height],
            showticklabels=False,
            showgrid=False,
        )
        fig.update_xaxes(showticklabels=True, showgrid=False)

        add_intensity_legend(fig, aggregation_method)

        figures.append(fig)

    return figures


def add_intensity_legend(
    fig: go.Figure, aggregation_method: AggregationMethod = AggregationMethod.median
):
    """
    Adds a color legend to the plotly figure indicating the intensity scale used for the peptides.

    :param fig: The plotly figure to add the legend to
    :param aggregation_method: The method used to aggregate peptide intensities
    """
    color_legend_trace = go.Scatter(
        x=[None],
        y=[None],
        mode="markers",
        marker={
            "colorscale": INTENSITY_COLOR_SCALE,
            "showscale": True,
            "cmin": 0,
            "cmax": 1,
            "colorbar": {
                "title": f"Relative intensity of peptide<br>(aggregated via {aggregation_method})",
                "x": 1.0,
                "len": 0.9,
                "thickness": 30,
                "title_side": "right",
            },
            "size": 10,
        },
        showlegend=False,
    )
    fig.add_trace(color_legend_trace)


def add_sequence_depth_to_plot(
    fig: go.Figure,
    coverage: list[int],
    protein_sequence_labels: list[str],
) -> None:
    """
    Adds a bar chart to the plotly figure indicating the sequencing depth at each position in the protein sequence.

    :param fig: The plotly figure to add the bar chart to
    :param coverage: A list indicating the sequencing depth at each position in the protein sequence
    :param protein_sequence_labels: A list of labels for the x-axis of the bar chart
    """
    sequence_depth_bar_chart = {
        "x": protein_sequence_labels,
        "y": coverage,
        "showlegend": False,
        "marker": {"color": PLOT_PRIMARY_COLOR},
        "hoverinfo": "y",
        "hovertemplate": "Sequencing depth at %{x}: %{y}",
    }
    fig.add_trace(go.Bar(**sequence_depth_bar_chart))


def add_peptide_to_plot(
    fig: go.Figure,
    normalized_intensity: float,
    peptide_match: PeptideMatch,
    protein_sequence_labels: list[str],
    row_index: int,
    offset: int,
    box_height: float,
    grouping: str = "",
) -> None:
    """
    Adds a rectangle to the plotly figure indicating the position of a peptide on the protein sequence.

    :param fig: The plotly figure to add the rectangle to
    :param normalized_intensity: The normalized intensity of the peptide (between 0 and 1)
    :param peptide_match: The PeptideMatch object containing the peptide sequence and its position on the protein
    :param protein_sequence_labels: A list of labels for the x-axis of the rectangle
    :param row_index: The index of the row to add the rectangle to
    :param offset: The offset to add to the y-axis position of the rectangle
    :param box_height: The height of the rectangle
    :param color_a: The color to use for the lowest intensity
    :param color_b: The color to use for the highest intensity
    :param grouping: The column in the metadata dataframe to group the samples by
    """
    x0, x1 = (
        peptide_match.start_location_on_protein,
        peptide_match.end_location_on_protein,
    )
    y0, y1 = row_index * box_height + offset, (row_index + 1) * box_height + offset
    # interpolate between the two colors
    color = (
        plotly.colors.sample_colorscale(INTENSITY_COLOR_SCALE, normalized_intensity)[0]
        if not np.isnan(normalized_intensity)
        else "#CCCCCC"
    )
    peptide_shape = {
        "type": "rect",
        "x0": x0 - 0.5,
        "y0": y0,
        "x1": x1 - 0.5,
        "y1": y1,
        "fillcolor": color,
        "line_color": color,
        "layer": "above",
    }
    fig.add_shape(**peptide_shape)
    # add invisible plotly object to the rectangle to show the peptide sequence when hovered over
    fig.add_trace(
        go.Scatter(
            x=protein_sequence_labels[
                peptide_match.start_location_on_protein : peptide_match.end_location_on_protein
                + 1
            ],
            y=[(y0 + y1) / 2] * len(peptide_match.peptide_sequence),
            text=[
                f"{grouping}: {peptide_match.metadata_group}<br>Peptide: {peptide_match.peptide_sequence}<br>"
                f"({peptide_match.start_location_on_protein}-{peptide_match.end_location_on_protein})<br>"
                f"Log2 Intensity: {peptide_match.intensity}"
            ]
            * len(peptide_match.peptide_sequence),
            mode="markers",
            marker={"opacity": 0, "size": 15},  # make marker invisible
            hoverinfo="text",
            hovertemplate="%{text}<extra></extra>",
            showlegend=False,
        ),
    )


def increment_coverage_inplace(coverage: list[int], protein_hit: ProteinHit) -> None:
    """
    Increments the coverage of a protein sequence by 1 for each position covered by the given protein hit.

    :param coverage: A list indicating the sequencing depth at each position in the protein sequence
    :param protein_hit: The ProteinHit object containing the start and end location of the peptide on the protein
    """
    start, end = (
        protein_hit.start_location_on_protein,
        protein_hit.end_location_on_protein,
    )
    coverage[start:end] = [value + 1 for value in coverage[start:end]]


def extract_peptide_from_slice(
    slice_df: pd.DataFrame,
    aggregation_strategy: AggregationMethod = AggregationMethod.median,
) -> pd.DataFrame:
    """
    Given multiple peptide datapoints, return a single peptide datapoint with the intensity value extracted from the
    slice of the peptide data.

    :param slice_df: A DataFrame containing multiple peptide datapoints for the same peptide sequence
    :param aggregation_strategy: The method to aggregate peptide intensities when multiple peptides map to the same
    sequence
    """
    if len(slice_df) == 1:
        return slice_df
    if aggregation_strategy == AggregationMethod.median:
        slice_df = slice_df.groupby("Sequence").median(numeric_only=True)
    elif aggregation_strategy == AggregationMethod.mean:
        slice_df = slice_df.groupby("Sequence").mean(numeric_only=True)
    else:
        raise ValueError(f"Unknown strategy: {aggregation_strategy}")
    return slice_df


def distribute_to_rows(
    peptide_matches: list[PeptideMatch],
) -> dict[str, list[list[PeptideMatch]]]:
    """
    Distributes peptide matches to rows such that no two peptides overlap in the same row.
    Greedy algorithm (see Interval Scheduling Problem).

    :param peptide_matches: A list of PeptideMatch objects to distribute to rows
    """
    if len(peptide_matches) == 0:
        raise ValueError(
            "Attempted to distribute empty list of peptide matches to rows in plot."
        )
    peptide_matches.sort(
        key=lambda peptide_match: peptide_match.start_location_on_protein
    )
    rows = {
        group_name: []
        for group_name in {
            peptide_match.metadata_group for peptide_match in peptide_matches
        }
    }
    for peptide_match in peptide_matches:
        # find the first row that does not overlap with the current peptide
        for row in rows[peptide_match.metadata_group]:
            if (
                row[-1].end_location_on_protein
                < peptide_match.start_location_on_protein
            ):
                row.append((peptide_match))
                break
        else:
            rows[peptide_match.metadata_group].append([peptide_match])
    return rows


def get_max_coverage(coverage: dict[str, list[int]]) -> int:
    """
    Gets the maximum coverage value from a dictionary of coverage lists.

    :param coverage: A dictionary mapping group names to coverage lists (i.e., lists that show how many peptides cover
    each position in the protein sequence)

    :return: The maximum coverage value across all groups
    """
    if len(coverage) == 0:
        raise ValueError(
            "Cannot calculate maximum coverage value: No coverage data provided."
        )
    return max(max(coverage) for coverage in coverage.values())
