import numpy as np
import pandas as pd
from backend.protzilla.importing.alphafold_protein_structure_load import (
    reduce_pae_to_per_amino_acid,
)
import pytest

# These test cases were generated by AI (Gemini) but have been manually checked


@pytest.fixture
def empty_cif_df():
    """Returns an empty atom_site DataFrame with required columns."""
    return pd.DataFrame(
        columns=[
            "_atom_site.label_entity_id",
            "_atom_site.label_seq_id",
            "_atom_site.label_atom_id",
        ]
    )


def test_no_duplicates(empty_cif_df):
    """Edge Case 1: Every residue has exactly one token.

    The PAE matrix should remain entirely untouched.
    """
    pae_matrix = np.array([[1.0, 2.0], [3.0, 4.0]])
    token_res_ids = [1, 2]

    result = reduce_pae_to_per_amino_acid(pae_matrix, token_res_ids, empty_cif_df)

    assert np.array_equal(result, pae_matrix)


def test_duplicates_fallback_to_first_token(empty_cif_df):
    """Edge Case 2: Multi-token residue, but length mismatch with CIF.

    Should fall back to keeping the first token (offset 0) and deleting the rest.
    """
    # 3 tokens: Residue 1 has 2 tokens, Residue 2 has 1 token.
    pae_matrix = np.array([[10, 11, 12], [20, 21, 22], [30, 31, 32]])
    token_res_ids = [1, 1, 2]

    # Keeping token 0 (first of res 1) and token 2 (res 2). Token 1 should be deleted.
    expected_indices = [0, 2]
    expected_matrix = pae_matrix[np.ix_(expected_indices, expected_indices)]

    result = reduce_pae_to_per_amino_acid(pae_matrix, token_res_ids, empty_cif_df)

    assert np.array_equal(result, expected_matrix)


def test_duplicates_keep_ca_atom():
    """Edge Case 3: Run length matches CIF length, and exactly one CA atom is found.

    Should keep the token corresponding exactly to the 'CA' atom position.
    """
    # 4 tokens: Residue 1 has 3 tokens, Residue 2 has 1 token.
    pae_matrix = np.diag([1.0, 2.0, 3.0, 4.0])
    token_res_ids = [1, 1, 1, 2]

    # CIF setup: 3 atoms for chain 1, residue 1. 'CA' sits at relative index 1.
    cif_df = pd.DataFrame(
        {
            "_atom_site.label_entity_id": ["1", "1", "1"],
            "_atom_site.label_seq_id": [1, 1, 1],
            "_atom_site.label_atom_id": ["N", "CA", "C"],
        }
    )

    # Expected: Keep global index 1 (the CA atom) and global index 3 (residue 2).
    # Global indices 0 and 2 should be wiped out.
    expected_indices = [1, 3]
    expected_matrix = pae_matrix[np.ix_(expected_indices, expected_indices)]

    result = reduce_pae_to_per_amino_acid(pae_matrix, token_res_ids, cif_df)

    assert np.array_equal(result, expected_matrix)


def test_duplicates_cif_match_but_no_ca_fallback():
    """Edge Case 4a: Run length matches CIF length, but no CA atom exists.

    Should fall back to keeping the first token (offset 0).
    """
    pae_matrix = np.diag([10, 20, 30])
    token_res_ids = [1, 1, 2]

    # CIF matches length (2 atoms), but neither is 'CA'
    cif_df = pd.DataFrame(
        {
            "_atom_site.label_entity_id": ["1", "1"],
            "_atom_site.label_seq_id": [1, 1],
            "_atom_site.label_atom_id": ["N", "O"],
        }
    )

    # Expected to keep global index 0 (fallback) and global index 2.
    expected_indices = [0, 2]
    expected_matrix = pae_matrix[np.ix_(expected_indices, expected_indices)]

    result = reduce_pae_to_per_amino_acid(pae_matrix, token_res_ids, cif_df)

    assert np.array_equal(result, expected_matrix)


def test_duplicates_cif_match_multiple_ca_fallback():
    """Edge Case 4b: Run length matches CIF length, but multiple CA atoms exist.

    Should fall back to keeping the first token (offset 0).
    """
    pae_matrix = np.diag([10, 20, 30])
    token_res_ids = [1, 1, 2]

    # CIF matches length (2 atoms), but both claim to be 'CA'
    cif_df = pd.DataFrame(
        {
            "_atom_site.label_entity_id": ["1", "1"],
            "_atom_site.label_seq_id": [1, 1],
            "_atom_site.label_atom_id": ["CA", "CA"],
        }
    )

    # Expected to keep global index 0 (fallback) and global index 2.
    expected_indices = [0, 2]
    expected_matrix = pae_matrix[np.ix_(expected_indices, expected_indices)]

    result = reduce_pae_to_per_amino_acid(pae_matrix, token_res_ids, cif_df)

    assert np.array_equal(result, expected_matrix)


def test_multiple_chains_tracking():
    """Edge Case 5: The system has multiple chains.

    Verifies that `current_chain_idx` increments whenever `res_id == 1` starts a run,
    and queries the correct stringified `_atom_site.label_entity_id`.
    """
    # Chain 1: res 1 (len 1), res 2 (len 1)
    # Chain 2: res 1 (len 2) -> Triggered by encountering 1 again
    token_res_ids = [1, 2, 1, 1]
    pae_matrix = np.diag([100, 200, 300, 400])

    cif_df = pd.DataFrame(
        {
            "_atom_site.label_entity_id": ["1", "1", "2", "2"],
            "_atom_site.label_seq_id": [1, 2, 1, 1],
            "_atom_site.label_atom_id": ["CA", "CA", "N", "CA"],
        }
    )

    # Chain 1, Res 1 (idx 0): len 1 -> Keep
    # Chain 1, Res 2 (idx 1): len 1 -> Keep
    # Chain 2, Res 1 (idx 2, 3): len 2 -> Matches CIF length for chain '2'.
    # CA is at relative index 1 (global idx 3). Global idx 2 is dropped.
    expected_indices = [0, 1, 3]
    expected_matrix = pae_matrix[np.ix_(expected_indices, expected_indices)]

    result = reduce_pae_to_per_amino_acid(pae_matrix, token_res_ids, cif_df)

    assert np.array_equal(result, expected_matrix)
