from backend.protzilla.all_steps import get_all_possible_steps


def test_get_all_possible_step_names():
    expected_step_names = {
        "MaxQuantImport",
        "DiannImport",
        "MsFraggerImport",
        "MetadataImport",
        "MetadataImportMethodDiann",
        "MetadataColumnAssignment",
        "PeptideImport",
        "EvidenceImport",
        "ExampleDatasetImport",
        "FastaImport",
        "FilterProteinsBySamplesMissing",
        "FilterProteinsByNumberOfValuesPerGroup",
        "FilterByProteinsCount",
        "FilterSamplesByProteinsMissing",
        "FilterSamplesByProteinIntensitiesSum",
        "OutlierDetectionByPCA",
        "OutlierDetectionByLocalOutlierFactor",
        "OutlierDetectionByIsolationForest",
        "TransformationLog",
        "TransformationInversion",
        "NormalisationByZScore",
        "NormalisationByTotalSum",
        "NormalisationByMedian",
        "NormalisationByWidthAdjustment",
        "NormalisationByReferenceProtein",
        "ImputationByMinPerDataset",
        "ImputationByMinPerProtein",
        "SimpleImputationPerProtein",
        "ImputationByKNN",
        "ImputationByNormalDistributionSampling",
        "FilterPeptidesByPEPThreshold",
        "FilterPeptidesByExistingProteins",
        "FilterPeptidesByExistingSamples",
        "DifferentialExpressionANOVA",
        "DifferentialExpressionTTest",
        "DifferentialExpressionLinearModel",
        "DifferentialExpressionMannWhitneyOnIntensity",
        "DifferentialExpressionMannWhitneyOnPTM",
        "DifferentialExpressionKruskalWallisOnIntensity",
        "DifferentialExpressionKruskalWallisOnPTM",
        "PlotClustergram",
        "PlotPrecisionRecallCurve",
        "PlotProteinCoverage",
        "PlotProtQuant",
        "PlotROC",
        "PlotScatterPlot",
        "PlotVolcano",
        "ClusteringKMeans",
        "ClusteringExpectationMaximisation",
        "ClusteringHierarchicalAgglomerative",
        "ClassificationRandomForest",
        "ClassificationSVM",
        "ModelEvaluationClassificationModel",
        "DimensionReductionTSNE",
        "DimensionReductionUMAP",
        "SelectPeptidesForProtein",
        "FLEXIQuantLF",
        "MultiFLEXLF",
        "PTMsPerSample",
        "PTMOverviewVisualization",
        "PTMBarVisualization",
        "PTMDetailsVisualization",
        "PTMsProteinAndPerSample",
        "ImputationByMinPerSample",
        "EnrichmentAnalysisGOAnalysisWithString",
        "EnrichmentAnalysisGOAnalysisWithEnrichr",
        "EnrichmentAnalysisGOAnalysisOffline",
        "EnrichmentAnalysisWithGSEA",
        "EnrichmentAnalysisWithPrerankedGSEA",
        "DatabaseIntegrationByGeneMapping",
        "DatabaseIntegrationByUniprot",
        "PlotGOEnrichmentBarPlot",
        "PlotGOEnrichmentDotPlot",
        "PlotGSEADotPlot",
        "PlotGSEAEnrichmentPlot",
    }

    steps = get_all_possible_steps()
    step_names = [step["method_name"] for step in steps]
    assert set(step_names) == expected_step_names
